import { useState } from 'react';
import NetworkSelector from './components/NetworkSelector';
import CaptureControls from './components/CaptureControls';
import PcapUploader from './components/PcapUploader';
import ChatPrompt from './components/ChatPrompt';
import './App.css';

function App() {
  const [selectedInterface, setSelectedInterface] = useState<string | null>(null);
  const [isCapturing, setIsCapturing] = useState(false);
  const [notification, setNotification] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [selectedDb, setSelectedDb] = useState<string | null>(null); // Add state for selected DB

  const handleStartCapture = async (duration: number) => {
    setError(null);
    setNotification(null);
    if (!selectedInterface) {
      setError('Selecciona una interfaz de red.');
      return;
    }
    setIsCapturing(true);
    setNotification('Capturando...'); // Mostramos el mensaje inmediatamente al pulsar el botón
    try {
      const res = await fetch('/api/capture/start', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ interface: selectedInterface, duration }),
      });
      const data = await res.json();
      if (data.capture_id) {
        // Ya no necesitamos establecer la notificación aquí porque ya se ha mostrado

        setTimeout(() => {
          setIsCapturing(false);
          setNotification(`Captura de ${duration} segundos finalizada.`); // Mensaje al finalizar
        }, duration * 1000);

      } else {
        setError('No se pudo iniciar la captura.');
        setIsCapturing(false);
      }
    } catch (e) {
      console.error('Error starting capture:', e);
      setError('Error al iniciar la captura.');
      setIsCapturing(false);
    }
  };

  // Function called when a DB is generated by PcapUploader
  const handleDbAvailable = (dbFile: string) => {
    setSelectedDb(dbFile); // Set the newly generated DB as selected
    setNotification(`Base de datos ${dbFile} generada y seleccionada.`);
  };

  return (
    <div className="min-h-screen bg-gray-50 bg-opacity-80 flex flex-col items-center justify-center p-4">
      <div className="w-full max-w-xl rounded-2xl shadow-lg bg-white bg-opacity-80 p-6 flex flex-col gap-6">
        <NetworkSelector selected={selectedInterface} onSelect={setSelectedInterface} disabled={isCapturing} />
        <CaptureControls
          disabled={!selectedInterface}
          onStart={handleStartCapture}
          isCapturing={isCapturing}
          statusMessage={notification || undefined}
        />
        <PcapUploader onDbReady={handleDbAvailable} />
        <ChatPrompt selectedDb={selectedDb} onDbSelect={setSelectedDb} /> {/* Pass state and setter */}
        {/* Notificaciones - Solo para errores y otras notificaciones, pero no para mensajes de captura */}
        <div className="h-10 text-center text-sm">
          {error && <span className="text-red-500">{error}</span>}
        </div>
      </div>
      <footer className="mt-8 text-xs text-gray-400">TFM &copy; 2025</footer>
    </div>
  );
}

export default App;
